In [68]:
import pandas as pd
import numpy as np

In [69]:
df = pd.read_csv('IMDB Dataset.csv',
                 encoding='latin-1'
                 ,engine='python',on_bad_lines='skip'
                 )
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [70]:
df['review']=df['review'].str.lower()
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [71]:

# remove html tags
import re
def remove_html_tags(text):
    pattern = re.compile(r'<.*?>')
    return pattern.sub(r'', text)

In [72]:
df['review'].apply(remove_html_tags)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [73]:
# remove urls
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [74]:
df['review'] = df['review'].apply(remove_urls)

In [75]:

# remove punctuation
import string
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [76]:
df['review'] = df['review'].apply(remove_punctuation)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production br br the filmin...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [77]:

#& Handle special characters and numbers
def remove_special_characters(text):
    return re.sub(r'[^a-zA-Z\s]', '', text)

In [78]:
# Install autocorrect (run once)
!pip install autocorrect -q
from autocorrect import Speller
spell = Speller(lang='en')

def correct_spelling(text):
    return ' '.join(spell(word) for word in text.split())

In [79]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    cleaned =[]
    for word in words:
        word = word.lower().strip(string.punctuation)
        if word and word not in stop_words:
            cleaned.append(word)    
    return ' '.join(cleaned)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\atiku\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [80]:
df['review'] = df['review'].apply(remove_stopwords)

In [81]:
!pip install emoji -q

In [82]:
import emoji

def remove_emojis(text):
    return emoji.replace_emoji(text, replace='')

In [83]:
df['review'] = df['review'].apply(remove_emojis)

In [86]:

# tokenization
from nltk.tokenize import word_tokenize,sent_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')

# using spacy for tokenization

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\atiku\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\atiku\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [87]:

#& Stemming 
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

def stem_text(text):
    words = text.split()
    stemmed_words = [stemmer.stem(word) for word in words]
    return ' '.join(stemmed_words)

In [88]:

#& Lemmatization
from nltk.stem import WordNetLemmatizer

wordnet_lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    lemmatized_words = [wordnet_lemmatizer.lemmatize(word,pos='v') for word in words]
    return ' '.join(lemmatized_words)